Add ability to use a local paper directory

diff --git a/bin/paper b/bin/paper
--- a/bin/paper
+++ b/bin/paper
@@ -19,8 +19,17 @@ export PAPER_COMPONENTS="${0:A:h:h}"
 bin="$PAPER_COMPONENTS/bin"
 export PATH="$bin:$PATH"
 
+local_bin="$PAPER_DIR/bin"
+if [ -d $local_bin ]; then
+  export PATH="$local_bin:$PATH"
+fi
+
 if [ -z $1 ] || [ $1 = '--help' ]; then
-  echo "Commands:"
+  if [ -d $local_bin ]; then
+    echo "Local commands:"
+    ls "$local_bin" | grep paper- | sed 's/paper-/  paper /g'
+  fi
+  echo "Core commands:"
   ls "$bin" | grep paper- | sed 's/paper-/  paper /g'
   exit 0
 fi
@@ -29,13 +38,21 @@ cmd="paper-$1"
 shift
 
 found_command=0
+if [ -d $local_bin ]; then
+  for f in $(ls "$local_bin" | grep paper-); do
+    [ $f != $cmd ] && continue
+    "$local_bin/$cmd" $@
+    exit $?
+  done
+fi
+
+
 for f in $(ls "$bin" | grep paper-); do
   [ $f != $cmd ] && continue
-  found_command=1
-  break
+  "$bin/$cmd" $@
+  exit $?
 done
 
-[ ! $found_command ] && echo "Command $cmd not found"
+echo "Command $cmd not found"
 
-"$bin/$cmd" $@
 
