Some changes to echo errors properly

diff --git a/bin/paper b/bin/paper
--- a/bin/paper
+++ b/bin/paper
@@ -5,12 +5,13 @@ if [ -z "$PAPER_DIR" ]; then
   # Find directory
   while [ ! -e "$dn/paper-defs.zsh" ]; do
     if [ "$dn" = "/" ]; then
-      echo -e "$(tput bold)paper-defs.zsh$(tput sgr0) not found in $(pwd) or any parent directory."
+      echo -e "$(tput bold)paper-defs.zsh$(tput sgr0) not found in $(pwd) or any parent directory." >&2
+
       exit 1
     fi
     dn="${dn:h}"
   done
-  echo -e "$(tput bold)Found paper directory$(tput sgr0): $dn"
+  echo -e "$(tput bold)Found paper directory$(tput sgr0): $dn" >&2
 
   export PAPER_DIR="$dn"
 fi
@@ -21,6 +22,12 @@ bin="$PAPER_COMPONENTS/bin"
 if [ -z $1 ] || [ $1 = '--help' ]; then
   echo "Commands:"
   ls "$bin" | grep paper- | sed 's/paper-/  paper /g'
+  exit 0
+fi
+
+# Echo directory name
+if [ $1 = '--dir' ]; then
+  echo "$PAPER_DIR"
   exit 0
 fi
 
